### ISSUE TITLE
Create Cocoapods specification

### ISSUE THREAD

**Issue by rsanchezsaez** [pixelglow/ZipZap#106]
There seem to be some unofficial ZipZap cocoapod specs floating around, but I think it'd be a good idea to submit an official one.

Some people seems to be having problem with the unofficial ones, as in [issue #105](https://github.com/pixelglow/ZipZap/issues/105).

**Comment by pixelglow** [comment]
Are you referring to https://cocoapods.org/?q=zipzap ? That is the official CocoaPod spec for ZipZap.

**Comment by rsanchezsaez** [comment]
Ah! I didn't realize there was that one. I tried adding `ZipZap` to my podfile and it didn't work, I guess because of case-sensivity. Thanks!

**Comment by pixelglow** [comment]
FYI, I originally named the project `zipzap` and so the official CocoaPods podspec followed that. But conventionally, Xcode projects are Pascal-cased and a lot of project setup assumes that (e.g. when Xcode automatically names the dynamic library version variable), so I eventually bit the bullet and renamed everything to `ZipZap`. Unfortunately, CocoaPods doesn't allow you to just change the case of a podspec, that's why it's still `zipzap` in the pod system.
