### ISSUE TITLE
Use of zipzap CocoaPod disables exception support project-wide

### ISSUE THREAD

**Issue by zygoat** [pixelglow/ZipZap#118]
This is a regression of a problem earlier reported and resolved in #78.

As of 8.0.4, inclusion of ZipZap via CocoaPods once again forces `GCC_ENABLE_OBJC_EXCEPTIONS = NO` on any target that uses it.

A temporary workaround is to manually set `GCC_ENABLE_OBJC_EXCEPTIONS = YES` at target level on any affected targets, but as described in #78, this causes a spew of warning output when running `pod install` (at least as of 0.38.2).

**Comment by tbaranes** [comment]
+1

**Comment by Doxxer** [comment]
+1

**Comment by pixelglow** [comment]
The issue should be fixed in the latest CocoaPods tool, try the 0.39.0 betas or later. Do tell me if that doesn't work out.

I appreciate you may not be 100% in control of your project's code, but it's generally [not a good idea](http://clang.llvm.org/docs/AutomaticReferenceCounting.html#exceptions) [to use Objective-C exceptions](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Exceptions/Articles/ExceptionsAndCocoaFrameworks.html#//apple_ref/doc/uid/TP40009045-SW1). In particular, ARC and the Cocoa frameworks are not exception-safe, but enabling exceptions in ZipZap would end up with a hidden link to libc++, so I made the call to disable exception support in the library.

**Comment by pixelglow** [comment]
Now that CocoaPods has stabilized on 0.39.0, please try using latest ZipZap with the new 0.39.0 release and see if this issue still occurs. 

cc. @rwbutler@rsanchezsaez

**Comment by tbaranes** [comment]
CocoaPods 0.39.0 solves this issue. I didn't get anymore the warnings.

**Comment by zygoat** [comment]
:+1:—CocoaPods 0.39 and zipzap 8.0.6 play nicely together once again in my project. Thanks!

**Comment by pixelglow** [comment]
No worries. Glad we could all resolve this, even if it took a while.
