### ISSUE TITLE
Asynchronous Extraction and Progress

### ISSUE THREAD

**Issue by RLovelett** [pixelglow/ZipZap#123]
@pixelglow do you have any recommendations/best practices for reading (extracting) a `ZZArchive` asynchronously?

Obviously I could just use GCD. Just wondering your thoughts.

Note: originally asked in #59

**Comment by pixelglow** [comment]
**We definitely support extraction on any single thread, single serial dispatch queue or equivalent.** That is, all access and extraction happens on the single thread or single serial dispatch queue.

That being said, ZipZap may work with more esoteric models. In particular, individual `ZZArchiveEntry` objects could be read or extracted in different threads or serial dispatch queues. I haven't vetted the code for this possibility, but since `ZZArchiveEntry` objects are read-only and independent of each other, it should work. On the other hand, making ZipZap eventually work with huge zip files *may* end up imposing some dependencies between the entry objects, although I'd still try to keep them independent. Is this extraction model important to you?

**Comment by RLovelett** [comment]
It definitely is; especially with progress reporting (like talked about in #59) which is why I originally brought it up there.

The project that we make use of ZipZap for generally only unzips archives > 250 MB. As you may expect, doing so on the main thread synchronously obviously is less than ideal. Currently I have my own class that inherits `ZZArchive` (it originally was just using extensions in Swift but I liked the inheritance better in the end) and implements the [NSProgressReporting Protocol](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSProgressReporting_Protocol/).

Internally it creates a serial queue and works through each of the elements in the entries array. I don't have the code in front of me right now but notionally it looks something like this:

```swift
func extract() {
  self.progress.totalUnitCount = entries.count
  let serialQueue = dispatch_queue_create("me.lovelett.namespace", DISPATCH_QUEUE_SERIAL)
  entries.forEach { (entry) in
    dispatch_async(serialQueue) {
       // Create directories as necessary
       // Write data from entry
       // Update the progress
       if (entries.last == entry) {
         // Clean-up and notify the callback that the async task is done
       }
    }
  }
}
```

I think having a convenience class like this that does both sync and async "extraction" would be helpful. That having been said, I understand it may not make sense for this library itself, I don't know what your intended scope or audience is. At the very least though I think providing a link to a Gist or something on the [recipes page](https://github.com/pixelglow/ZipZap/wiki/Recipes) may be a good first step.

**Comment by pixelglow** [comment]
> As you may expect, doing so on the main thread synchronously is less than ideal.

You can extract on a single thread or single serial dispatch queue, it doesn't have to be the main thread.

> Internally it creates a serial queue and works through each of the elements in the entries array. 

The code iterates in one thread and then extracts on a different single thread/queue. For now, this should work, and after I've finished supporting large archives, this should still work but I can't guarantee it now (I may end reimplementing this iteration lazily for example). The safer alternative is to move the iteration code to the serial queue as well.

> Currently I have my own class that inherits ZZArchive ... and implements the NSProgressReporting Protocol.

If you have a granular `NSProgressReporting` implementation, I'd love to see it in mainline! The idea is we should be able to see progress down to the chunk level e.g. even within the various streaming objects.

> I think having a convenience class like this that does both sync and async "extraction" would be helpful. That having been said, I understand it may not make sense for this library itself, I don't know what your intended scope or audience is.

I'm trying to keep ZipZap minimal and composable, a platform others can build on top of. Otherwise, including all combination of possibilities will end up complicating the API and the understanding of the API, and including code that not everyone wants. For example, not every needs to extract to a file, so there's no direct API for that.

That being said, I'd be OK with really common idioms making it to the API.

As for sync vs async, it's a tougher call. I like a lot of callback-based API's e.g. node.js because they don't block the main thread by default. On the other hand, an extract-only async may not be the right level of granularity, for example you might want to do something heavy to the extracted data in that other thread and not have to hand the data back to the calling thread for further processing -- creating a `CGImageRef` bitmap out of extracted data comes to mind, or immediately writing out the data to a file, or doing something that requires 2 or more entries. Sync API's are simpler to understand, reason about and compose. On the balance of things, I'd keep the API sync.

> At the very least though I think providing a link to a Gist or something on the recipes page may be a good first step.

For sure. If you have a suitable example, perhaps by expanding out your snippet while keeping it focussed, I'll include it in the recipes page.

**Comment by RLovelett** [comment]
I'll work on distilling the class down the minimal and try and post by Friday.
