### ISSUE TITLE
Entries with file names with certain characters are set to nil

### ISSUE THREAD

**Issue by jjxtra** [pixelglow/ZipZap#125]
Download this zip file at http://www.dafont.com/search.php?q=quartzo
The second file has an entry with a nil file name. The file name should be "QUARTZO ∏ PERSONAL USE ONLY"

**Comment by pixelglow** [comment]
Thanks for reporting that, looks like a bug alright!

The actual filename is "QUARTZO ? PERSONAL USE ONLY.ttf" where ? is the hex byte `b8`. Since this is surrounded by space chars `20`, this cannot be UTF-8. Unfortunately the current API considers the filename to be UTF-8 by default, whereas the Zip format is documented to be CP-437 by default.

The immediate workaround is to declare the actual filename encoding when initialising the `ZZArchive` object. So this would be something like `NSISOLatin1StringEncoding` (for Latin-1) or `kCFStringEncodingDOSLatinUS` (for CP-437) as appropriate. Note that neither Latin-1 nor CP-437 actually encode byte `b8` as ∏.

I'll fix this issue soon by going back to the Zip file spec for file names, which is a breaking change, and also allowing finer grained encodings, see #120.

**Comment by jjxtra** [comment]
Super, that sounds great. Your library has been very useful in my app, You Doodle.

**Comment by jjxtra** [comment]
By the way I tested the latest code and it no longer fails on this file name, so I am closing this issue.
