### ISSUE TITLE
Can't open libzip file, error on EOCD Read Error

### ISSUE THREAD

**Issue by pepsin** [pixelglow/ZipZap#127]
[android_no_padding.txt](https://github.com/pixelglow/ZipZap/files/33801/android_no_padding.txt)

Attach the Zip file for you guys to check. Due to Github upload file restrition, I change the file type to txt.

If there's any problem, I will send the file by other means.

**Comment by pixelglow** [comment]
I had a quick look with `zipinfo` and by running `ZipZap` on Mac OS X, checking for `fileName` and `newData()`, didn't see any errors -- there's a single file called "FILE" on the archive. Please show the code you used to access this archive.

**Comment by pepsin** [comment]
I finally fix this by adding correct padding in the EOCD's comment place.

But I think ZipZap's EOCD's sanity check should be more loose.

The libzip and some other archive lib are more open on the padded Zip file.

Especially the padding on the file end and the padding isn't correct state the comment length.

**Comment by pixelglow** [comment]
Not sure I understand the issue here.

I wrote the following to access your file:
```Swift
let newArchive = try! ZZArchive(URL: NSURL(fileURLWithPath: "android_no_padding.zip"), options: nil)
for entry in newArchive.entries {
    print("\(entry.fileName)")
    
    let data = try! entry.newData()
    print("\(data)")
}
```

... and no errors were reported, the filename **FILE** was printed and also the data in the zip entry.

I do understand the EOCD sanity check but the zip file you attached didn't seem to trigger it.

**Comment by pepsin** [comment]
[test.txt](https://github.com/pixelglow/ZipZap/files/35204/test.txt)

I attach a new one. See if this have the issue. My local testing shows this trigger that problem.

**Comment by pixelglow** [comment]
Thanks for the effort in producing these test zips.

I believe ZipZap is working correctly here. In *test.zip*, the zip comment length field is zero but there are additional non-spec bytes beyond the EOCD, as you've stated.

Since ZipZap scans 64K backwards from EOF for the EOCD signature, it needs to sanity-check the EOCD and one of the checks is that there are no bytes after the EOCD. If it were to weaken the check, it may need to scan back further than 64K for the EOCD, since there could be arbitrary amount of data after the EOCD. The edge case would result in scanning the entire file e.g. if someone passed a non-Zip file to the library.

A couple of solutions:
* Implement an additional forward scanning mode. This would kill performance though, since the whole point of the CD is to have a minimal read for the metadata.
* Implement scanning backward in chunks. This would be complicated and probably interfere with planned work on overcoming the mmap limit.

What do you guys think?

**Comment by pepsin** [comment]
I think leave the 64K around will be OK.

But if the comment length is inconsistent with the final padding length, I think should let it pass. In fact, most of this problem is causing by padding the zip file for some encryption, and in that situation the padding length always small than 128K. 

Or, give an option for loosing check, or, write this in the README to notify guys who may encounter this problem and still keep the sannity check.

I think keep the sannity check is fine. As long as people know what the comment is.

**Comment by pixelglow** [comment]
> But if the comment length is inconsistent with the final padding length, I think should let it pass. In fact, most of this problem is causing by padding the zip file for some encryption, and in that situation the padding length always small than 128K.

I'll keep the comment length consistency check. Your padding example is only one issue; as a generalist library, once we loosen the check we would have to deal with other potential issues like >64K padding.

> Or, give an option for loosing check, or, write this in the README to notify guys who may encounter this problem and still keep the sannity check.

I'm happy to accept a pull request to implement a backward scan, fenced by an option to ignore any bytes after the EOCD record. I would try to keep that in sync with any mmap limit work.

> I think keep the sannity check is fine. As long as people know what the comment is.

Good call. However we should update the documentation comments around `archiveWithURL:error:` and `archiveWithData:error` rather than the README. I'm happy to accept a pull request to update the `@param error` documentation comment with the possible errors; I may do this myself when I clean up the error enum for better Swift usage.
