### ISSUE TITLE
ZipZap and own GitHub project

### ISSUE THREAD

**Issue by ekuester** [pixelglow/ZipZap#144]
ZipZap.framework for OSX compiled with Xcode under El Capitan without problems, using of xctool is possible, too. I use this framework in a project of mine to show images from a zipped archive. Now my questions: If I submit this project to GitHub, can I include the zipzap.framework (the compiled version), so that every interested can compile this project for himself? Will you allow this, have I to include the license.txt file, whatsoever?
Kind regards, Erich Kuester from Germany

**Comment by pixelglow** [comment]
At a minimum, you can include the framework with the license.txt and acknowledgement merged with your license.txt or README. Just include a link to our main GitHub page.

However since we're all using GitHub, it's best to use either *git submodules* or *git subtrees* to incorporate ZipZap at the workspace level. Alternatively you can also use Carthage or CocoaPods to include ZipZap. This way your project will always get the latest changes to ZipZap and we can also more easily incorporate your changes back to ZipZap.

**Comment by ekuester** [comment]
OK, I will have a look on all that ... It's my first project with GitHub, so all is quite new to me. I'll keep you informed.

**Comment by ekuester** [comment]
I uploaded just now the source of my program, not complete in some aspects, but I am learning. Please have a look at [https://github.com/ekuester/Swift-Show-ScrollView-FullScreen](url) . If you have any complaints, don't hesitate to mention.

**Comment by pixelglow** [comment]
Looks good to me, I just looked at it briefly!
